name: build_manual

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: "Docker Pull"
        run: |
          docker pull adhocore/phpfpm:7.4 || true
      - name: "[7.4] Build and push"
        id: docker_build_74
        uses: docker/build-push-action@v4
        with:
          push: true
          file: 7.4.Dockerfile
          tags: adhocore/lemp:7.4
          platforms: linux/amd64,linux/arm64
      - name: "[7.4] Test"
        run: |
          docker run --name lemp74 adhocore/lemp:7.4 &
          sleep 60
          docker exec $(docker ps -q -f 'name=lemp74') netstat -ant | grep -E '0:11300|0:11211|1:9300|1:9200|::9000|0:6379|1:5432|0:3306|0:88|0:74|0:25'
          PORTS=$(docker exec $(docker ps -q -f 'name=lemp74') netstat -ant | grep -E '0:11300|0:11211|1:9300|1:9200|::9000|0:6379|1:5432|0:3306|0:88|0:74|0:25' | wc -l | xargs)
          sleep 1 && docker stop lemp74 > /dev/null || true
          [[ "11" == "$PORTS" ]] || { echo '[7.4] Not all ports are open' && exit 1; }

